export const AuthActionTypes = {
  // Auth Actions
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_STUDENT_SUCCESS: 'LOGIN_STUDENT_SUCCESS',
  LOGIN_ADMIN_SUCCESS: 'LOGIN_ADMIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  LOGOUT: 'LOGOUT'
}
